### ISSUE TITLE
cannot find utils_all module

### ISSUE THREAD

**Issue by Ttchance** [nju-websoft/KG-ICL#1]
hi，Your paper is very helpful, but in the data preprocessing section, it seems that utils_all is an internal file, yet I cannot seem to find the utils_all module. I would greatly appreciate it if you could provide some clarification.

**Comment by yncui-nju** [comment]
Thank you for your attention to our work. 

I have addressed this issue by adding the following line of code to each `data_process.py` file:  
`sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))`

If you still cannot load `utils_all`, please copy the `utils_all.py` file from the `datasets` directory into each subdirectory. 
I hope this helps resolve your issue.
