### ISSUE TITLE
Little questions about downstreams task

### ISSUE THREAD

**Issue by gsanou** [nju-websoft/KG-ICL#2]
Hello, 

First of all, thank you for this tool. I success to reproduce your result. I'm interested to know how can i use the save model in downstream task. Can you give me any clues to extract embeddings of my entities in order to use it in downstream task like classification, clustering or visualisation. I'm already familiarised with pykeen which provides a way to extract them.

Thank you for your time.

Best, 
GS

**Comment by yncui-nju** [comment]
Thank you for your interest in our work! 

KG-ICL generates different embeddings for the same entity based on the specific query. For example, the embeddings for "London" differ between the queries (Bob, worksFor, ?) and (Bob, liveIn, ?). This type of network is also known as a "conditional message-passing neural network." Therefore, directly extracting entity embeddings is not feasible.

Perhaps you can transform downstream tasks into link prediction tasks (subject, relation, ?). For example, for a node classification task, you could create a virtual node for each class type. Then, add an edge (entity, typeIsClassX, ClassX) for each entity of that type, setting the candidate space for Class to these virtual class entity nodes.

I hope this is helpful to you.

**Comment by gsanou** [comment]
Thank you for your reply. I get it now. In the case of link prediction i'm also interested on it but i don't have any clue to implement it with my trained model. Can you please provide little documention to this. 
Thank you

**Comment by yncui-nju** [comment]
Are you asking how to use the model trained with [src/pretrain.py](https://github.com/nju-websoft/KG-ICL/blob/main/src/pretrain.py)? It will be saved in the checkpoint/pretrain/ folder. You can copy this model path as the args.checkpoint_path in evaluation.py. This way, you can use your pre-trained model for inference.

**Comment by gsanou** [comment]
ok I get it now. thank you. I close the issue. 

Best, 
GS
